# Generated by Django 4.2.1 on 2023-05-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3. Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '4. Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '1. Teachers'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='interested_categories',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(),
        ),
    ]
